name: build-release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  build-release:
    name: build-release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasi
      - run: cargo b -r
      - uses: softprops/action-gh-release@v2
        with:
          files: target/wasm32-wasi/release/*.wasm
